### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by wyattbenno777** [SNUCP/elsa#2]
What license is this under? Please add to the repo.

**Comment by sp301415** [comment]
Hi!
We are planning some rewrites on the code and will add a license afterward. While we are not yet certain which license we will use, it will be a permissive one.

**Comment by wyattbenno777** [comment]
Thanks. FYI by just adding rayon to the encoder:

`
No parallelization: 
commit (no zk): 207.678625ms

With parallelization:
commit (no zk): 54.120833ms
`

Did the other libs (FRI, Brakedown) you tested in the paper have rayon enabled?

**Comment by sp301415** [comment]
Hi,

Thanks for the heads up! While running benchmarks, we only considered single-thread performances for couple of reasons: It was much easier to implement, and we thought multi-thread performance was not a good metric since it is inherently more prone to external variances.

IIRC, the NTT backend we use (concrete-ntt) and random samplers are not thread-safe currently, so just adding rayon would likely output wrong results. That being said, some parts of the code can be easily parallelized by just allocating some sub-structs multiple times, so you can definitely speed things up with increased memory usage.

Hope this helps!
